recipe: default.v1

assistant_id: 20240825-214304-vertical-bend


language: en

pipeline: 
  # - name: spacy.SpacyNLP
  - name: WhitespaceTokenizer
  # - name: spacy.SpacyTokenizer
  # - name: spacy.SpacyFeaturize
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
    cache_dir: null
  - name: RegexFeaturizer
    use_word_boundaries: True
    number_additional_patterns: 10 
  - name: RegexEntityExtractor
    use_lookup_tables: True
    use_regexes: True
    use_word_boundaries: True
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
 
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
  - name: DucklingEntityExtractor 
    dimensions: ["number"]
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
    cache_dir: null

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    priority: 4
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
    priority: 3
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    priority: 2
